project:
  type: website

website:
  title: "StrainCascade"
  navbar:
    left:
      - href: index.qmd
        text: Overview
      - href: installation.qmd
        text: Installation
      - href: usage.qmd
        text: Usage
      - href: tutorial.qmd
        text: Tutorial
#      - href: documentation.qmd
#        text: Documentation
      - href: dependencies.qmd
        text: Dependencies
      - href: publications.qmd
        text: Publications
      - href: license.qmd
        text: License
        
  page-navigation: true

format:
  html:
    theme: flatly
    css: 
      - styles.css
      - custom.css
    toc: true
    toc-depth: 3
    toc-title: Contents
    number-sections: true
    highlight-style: github
    code-fold: true
    code-tools: false
    mainfont: Helvetica

editor: visual