name: Render and Publish Quarto Website

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  schedule:
    - cron: '0 0 * * 0'  # Run every Sunday at midnight

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Set up Quarto
        uses: quarto-dev/quarto-actions/setup@v2

      - name: Set up R
        uses: r-lib/actions/setup-r@v2

      - name: Install R and Quarto Dependencies
        working-directory: quarto_webpage
        run: |
          Rscript -e 'install.packages(c("renv", "knitr", "rmarkdown"))'
          Rscript -e 'renv::restore()'  # Ensure renv restores the environment

      - name: Render Quarto Project
        working-directory: quarto_webpage
        run: |
          quarto render .  # Render the Quarto project

      - name: Publish to GitHub Pages
        working-directory: quarto_webpage/_site
        uses: quarto-dev/quarto-actions/publish@v2
        with:
          path: .  # Specify the path to the built site
          target: gh-pages
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

